### ISSUE TITLE
training log

### ISSUE THREAD

**Issue by ChengShiest** [clovaai/ECLIPSE#10]
Hello,

Could you provide the training log, especially for step 0, to facilitate reproduction?

**Comment by qjadud1994** [comment]
Hi.

Which continual learning scenarios for step 0 do you need, such as ade-ps 100-10?

And, are there reproduction issues for step 0?

**Comment by ChengShiest** [comment]
It would be great if you could provide ade-ps 100-10 and coco_ps 83_5. There's nothing wrong with reproduction; it's just that the training at step 0 takes too long. :)

**Comment by qjadud1994** [comment]
If you use the [provided step 0 pre-trained weights](https://github.com/clovaai/ECLIPSE?tab=readme-ov-file#quick-start), we can skip the step 0 training process.
