### ISSUE TITLE
How should I understand these symbols?

### ISSUE THREAD

**Issue by BaofengZan** [clovaai/ECLIPSE#11]
Firstly, I would like to thank you for your work. Regarding the code, I have some doubts.
What do these variables represent in the training script?
1. ONT.BASE_CLS 83    --  Is this the number of categories (COCO dataset)?
2. CONT.INC_CLS 5      -- Is this also the number of categories? And it's not in the above 83 categories? 
3. base_queries=100.   -- What does this mean?  Can it be modified?
4.  num_prompts=10.   -- as above
5. 
     If I have a set of data with 10 categories. I have already trained step 0. When I proceed to train step 1, it's still these 10 categories but with different images. Should I set BASE_CLS equal to INC_CLS, both as 10?

**Comment by qjadud1994** [comment]
Hi.

You need to understand the continual segmentation settings.

![image](https://github.com/clovaai/ECLIPSE/assets/20681582/25bd3095-3287-4668-8da7-c3055e279ec2)

1. `CONT.BASE_CLS` means the number of classes at step 0, termed base classes. The total number of classes for COCO-Panoptic dataset is 133. We split the 133 classes into 83 and 50 classes. `CONT.BASE_CLS = 83` means that we set the number of base classes for COCO as 83.

2. `CONT.INC_CLS`  means the number of incremented classes. `CONT.INC_CLS = 5` means that we repeatedly guide 5 new classes to the model and repeat this process 10 times (until the number of total incremented classes becomes 50).

3. `base_queries` is a hyperparameter, and we set it to the number of base classes: `base_queries = CONT.BASE_CLS`.

4. `num_prompts` is also a hyperparameter, `num_prompts = CONT.INC_CLS` but the minimum value of num_prompts is set to 10.

5. `BASE_CLS` is set to the number of classes at step 0 and `INC_CLS` is set to 10.
