### ISSUE TITLE
why classifier predict old classes?

### ISSUE THREAD

**Issue by wendyhuang2021** [clovaai/ECLIPSE#14]
Hi!

I found that the classification head predicts the old classes. For example, in the VOC 19-1 setting (starting from step 0), step 1 predicts 21 classes, including no-object.

Why doesn't step 1 just handle the two new classes and the novel queries? I thought the model would not suffer from class confusion this way.

If I misunderstood your code, please let me know.

Original-
every query go into all classifier:
sem_seg_head.predictor.class_embed.cls.0 → no-object
sem_seg_head.predictor.class_embed.cls.1 → 19 classes
sem_seg_head.predictor.class_embed.cls.2 → 20 classes

The way I thought maybe better-
base queries, novel queries → sem_seg_head.predictor.class_embed.cls.0 → no-object
base queries                         → sem_seg_head.predictor.class_embed.cls.1 → 19 classes
novel queries                        → sem_seg_head.predictor.class_embed.cls.2 → 1 classes

**Comment by qjadud1994** [comment]
Hi.

You might misunderstand the code.

Our classifier is implemented the same as the second way you mentioned.
~~~
base queries, novel queries → sem_seg_head.predictor.class_embed.cls.0 → no-object
base queries → sem_seg_head.predictor.class_embed.cls.1 → 19 classes
novel queries → sem_seg_head.predictor.class_embed.cls.2 → 1 classes
~~~

Please refer to it:
https://github.com/clovaai/ECLIPSE/blob/4b66c6764d6965e3138310f6f23145e0e34aa772/continual/modeling/classifier.py#L49-L70

**Comment by wendyhuang2021** [comment]
Thanks for your reply!
I think the following information might also be helpful if someone is confused about this.

[mask2former/modeling/transformer_decoder/mask2former_transformer_decoder.py](https://github.com/clovaai/ECLIPSE/blob/4b66c6764d6965e3138310f6f23145e0e34aa772/mask2former/modeling/transformer_decoder/mask2former_transformer_decoder.py#L442)
```
# in 
ret["classes"] = [cfg.CONT.BASE_CLS] + cfg.CONT.TASK*[cfg.CONT.INC_CLS]
```
