### ISSUE TITLE
Some problems about test ,visualization and Customed dataset

### ISSUE THREAD

**Issue by JFJ-Bin** [clovaai/ECLIPSE#17]
Thanks for your great work! how can i test the model and visualize the predict? And how can I use my customed dataset to train? Thanks! @qjadud1994

**Comment by qjadud1994** [comment]
Hi. 
I recommend you check the Mask2Former implementation, which is our baseline code.
Also, after checking [the dataset preprocessing part](https://github.com/clovaai/ECLIPSE/blob/main/mask2former/data/dataset_mappers/mask_former_panoptic_dataset_mapper.py), you can use your customer dataset.
