### ISSUE TITLE
environment and package version

### ISSUE THREAD

**Issue by wendyhuang2021** [clovaai/ECLIPSE#2]
Hi! May you provide the precise packages & environment version? Such as python, torch, torchvision?

**Comment by wendyhuang2021** [comment]
cuda=11.8
torch=2.1.2
If just use a single gpu, torch 1.9 not work. Update torch to 2.1.2, or change "SyncBN" -> "BN"

above it's work for me.

**Comment by qjadud1994** [comment]
My environment setting is as follows
torch=1.13.0
torchvision=0.14.0
cuda=11.7
cudnn=8.3

I follow [Mask2Former's installation instructions](https://github.com/facebookresearch/Mask2Former/blob/main/INSTALL.md), so I recommend checking them out.

**Comment by wendyhuang2021** [comment]
Thanks for your great work and replay!
