### ISSUE TITLE
FLOPs Calculation Tool

### ISSUE THREAD

**Issue by Ze-Yang** [clovaai/ECLIPSE#20]
Could you share the code to calculate the FLOPs reported in the paper? May I know what input resolution is used to calculate the FLOPs? Thanks.

**Comment by qjadud1994** [comment]
We used [the analysis tool](https://github.com/facebookresearch/Mask2Former/blob/9b0651c6c1d5b3af2e6da0589b719c514ec0d69a/tools/analyze_model.py) provided by Mask2Former.
