### ISSUE TITLE
About training cost

### ISSUE THREAD

**Issue by zhengyuan-xie** [clovaai/ECLIPSE#4]
Hi, thanks for your work! I want to reproduce the result and wonder the number of GPUs used in these experiments and the training time, hope you can help me!

**Comment by qjadud1994** [comment]
We mainly conduct all experiments using 4 V100 GPUs.
We also checked that the performance difference between using 4 V100s and 8 V100s was minimal.

**Comment by zhengyuan-xie** [comment]
> We mainly conduct all experiments using 4 V100 GPUs. We also checked that the performance difference between using 4 V100s and 8 V100s was minimal.

Thanks for your fast reply!
