### ISSUE TITLE
Possible problems and some questions about the paper 

### ISSUE THREAD

**Issue by ZhuYuChenNO1** [clovaai/ECLIPSE#6]
Hello! Thank you for your great work. I have some questions about your paper.

1. In Table 1, For this row of FT data, it seems your data comes from CoMFormer. However, can 100-5 (11 tasks) and 100-50 (2 tasks) be written in the wrong positions?
2. In Table 1, Regarding the performance of CoMFormer, why is the data for 100-50 (2 tasks) inconsistent with the original paper?

**Comment by qjadud1994** [comment]
1. Oh! Thank you for pointing out. It is an error as you mentioned. 
2. We successfully reproduced the performance of CoMFormer for all scenarios, except only for 100-50 (2 tasks). We tried to reproduce the performance of CoMFormer, PLOP, and MiB on the 100-50 scenario by changing various hyperparameters, but we failed. Therefore, we reported our reproduced performances of these methods on the 100-50 scenario.

**Comment by ZhuYuChenNO1** [comment]
> 1. Oh! Thank you for pointing out. It is an error as you mentioned.
> 2. We successfully reproduced the performance of CoMFormer for all scenarios, except only for 100-50 (2 tasks). We tried to reproduce the performance of CoMFormer, PLOP, and MiB on the 100-50 scenario by changing various hyperparameters, but we failed. Therefore, we reported our reproduced performances of these methods on the 100-50 scenario.

Thank you for getting back to me. My question has been solved. 
As a side note,Hope you can find the error cause the fail of reproduce your ADE20K-Semantic 100-50. However, this matter is not within the scope of discussion for this issue. So, I will close this issue.
