### ISSUE TITLE
RuntimeError: Global alloc not supported yet

### ISSUE THREAD

**Issue by Ze-Yang** [clovaai/ECLIPSE#7]
I came across an error when I ran the codes (step 1 training). Have you seen this error before?

![Screenshot from 2024-06-05 15-31-01](https://github.com/clovaai/ECLIPSE/assets/42920710/d8b552fa-b0c8-4ae8-84e9-04df3386c897)

**Comment by qjadud1994** [comment]
I have never seen this error before.
`batch_dice_loss_jit` is part of Mask2Former code, so please check [their environment settings](https://github.com/facebookresearch/Mask2Former/blob/main/INSTALL.md).

**Comment by ahhnchangjun** [comment]
> I came across an error when I ran the codes (step 1 training). Have you seen this error before?
> 
> ![Screenshot from 2024-06-05 15-31-01](https://private-user-images.githubusercontent.com/42920710/336733089-d8b552fa-b0c8-4ae8-84e9-04df3386c897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjcwNDksIm5iZiI6MTcxODM2Njc0OSwicGF0aCI6Ii80MjkyMDcxMC8zMzY3MzMwODktZDhiNTUyZmEtYjBjOC00YWU4LTg0ZTktMDRkZjMzODZjODk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEyMDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDAzN2VmZTA3MDYxOGFiMWUyYTMyNWUxNThlNGQxMjY1NDhjNzNkYzI5NjJiNTkxNTJkMzE2MDMyOGM0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cui7xGRUpLjbVAc7xBvL0Ig5jgehbdJmtcRYFdK1pdQ)

I got the same error, did you solve the problem ?

**Comment by hanminpay** [comment]
You can delete the corresponding JIT packaging
