### ISSUE TITLE
index of no-obj

### ISSUE THREAD

**Issue by aooating** [clovaai/ECLIPSE#9]
In logit manipulation implementation, no-obj seems like the last class, while its index is 0 in ADE20K_SEM_SEG_CATEGORIES. I want to know if there is an error, or my understanding is wrong. Looking forward to the author's reply.

**Comment by aooating** [comment]
# [1] : no_obj, (we don't have bkg class)
self.class_embed = IncrementalClassifier(
                        [1] + classes, 
                        channels=hidden_dim, 
                        bias=bias, 
                        deep_cls=deep_cls,
                    )
The code of classifier indicates the index of no_obj is 0, if there is an error?

**Comment by qjadud1994** [comment]
It is not an error.

https://github.com/clovaai/ECLIPSE/blob/9a7cdfbc3615537ff3b4f54af69a4974aff7608f/continual/modeling/classifier.py#L66-L70

Please check the implementation of `IncrementalClassifier`.
The first class is placed to the last index.
